'use client';

import Header from '@/components/Header';
import { Ticket, Search, Filter, AlertCircle, CheckCircle2, Clock, ArrowLeft } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { motion } from 'framer-motion';

const tickets = [
  { id: 'SNOW-4492', title: 'Oracle 11g Retirement & Migration', status: 'Open', priority: 'High', type: 'Remediation', created: '2026-06-28', assignee: 'Cloud Migration Team' },
  { id: 'INC-09283', title: 'Halt Deployments - Payment Gateway Collision', status: 'In Progress', priority: 'Critical', type: 'Incident', created: '2026-06-28', assignee: 'Release Management' },
  { id: 'SNOW-4491', title: 'Java 8 Upgrade to Java 17', status: 'Pending Approval', priority: 'Medium', type: 'Remediation', created: '2026-06-27', assignee: 'App Development' },
  { id: 'SNOW-4301', title: 'Decommission Legacy Siebel CRM', status: 'Closed', priority: 'High', type: 'Retirement', created: '2026-06-15', assignee: 'EA Team' },
  { id: 'SEC-1102', title: 'Legacy Auth V1 Replacement', status: 'Open', priority: 'Critical', type: 'Security', created: '2026-06-25', assignee: 'Identity & Access' },
];

export default function TicketsDashboard() {
  const router = useRouter();

  return (
    <div className="min-h-screen bg-[#030712] flex flex-col">
      <Header />
      
      <main className="flex-1 pt-24 px-4 sm:px-6 lg:px-8 pb-12">
        <div className="mx-auto max-w-7xl">
          
          <div className="mb-8 animate-fade-up">
            <button 
              onClick={() => router.back()} 
              className="flex items-center gap-2 text-sm text-surface-400 hover:text-surface-50 mb-6 transition-colors"
            >
              <ArrowLeft size={16} /> Back
            </button>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-surface-900 border border-surface-800 text-xs font-semibold text-primary mb-4">
              <Ticket size={14} /> Service Management
            </div>
            <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight text-surface-50 mb-4">
              Remediation & Incidents
            </h1>
            <p className="text-lg text-surface-400 max-w-2xl">
              Track automated tickets generated by the EA Intelligence engine for technology remediation and deployment collisions.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="glass-card p-6 border-t-4 border-t-primary">
              <div className="text-surface-400 text-sm font-semibold mb-2">Total Active Tickets</div>
              <div className="text-4xl font-bold text-surface-50">124</div>
            </motion.div>
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="glass-card p-6 border-t-4 border-t-danger">
              <div className="text-surface-400 text-sm font-semibold mb-2">Critical Priority</div>
              <div className="text-4xl font-bold text-danger">18</div>
            </motion.div>
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }} className="glass-card p-6 border-t-4 border-t-warning">
              <div className="text-surface-400 text-sm font-semibold mb-2">Pending Approval</div>
              <div className="text-4xl font-bold text-warning">45</div>
            </motion.div>
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4 }} className="glass-card p-6 border-t-4 border-t-success">
              <div className="text-surface-400 text-sm font-semibold mb-2">Resolved (30d)</div>
              <div className="text-4xl font-bold text-success">89</div>
            </motion.div>
          </div>

          <div className="glass-card overflow-hidden">
            <div className="p-4 border-b border-surface-800 flex items-center justify-between bg-surface-900/30">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-surface-500" size={16} />
                <input 
                  type="text" 
                  placeholder="Search tickets..." 
                  className="bg-surface-950 border border-surface-800 rounded-lg pl-10 pr-4 py-2 text-sm text-surface-100 focus:outline-none focus:border-primary w-64 transition-colors"
                />
              </div>
              <button className="flex items-center gap-2 px-4 py-2 bg-surface-800 hover:bg-surface-700 text-surface-200 rounded-lg text-sm transition-colors border border-surface-700">
                <Filter size={16} /> Filter
              </button>
            </div>
            
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="bg-surface-900/50 border-b border-surface-800 text-surface-400 text-xs uppercase tracking-wider">
                    <th className="p-4 font-semibold">Ticket ID</th>
                    <th className="p-4 font-semibold">Title</th>
                    <th className="p-4 font-semibold">Status</th>
                    <th className="p-4 font-semibold">Priority</th>
                    <th className="p-4 font-semibold">Type</th>
                    <th className="p-4 font-semibold">Created</th>
                    <th className="p-4 font-semibold">Assignee</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-surface-800">
                  {tickets.map((ticket, index) => (
                    <motion.tr 
                      key={ticket.id} 
                      initial={{ opacity: 0, x: -20 }} 
                      animate={{ opacity: 1, x: 0 }} 
                      transition={{ delay: index * 0.1 }}
                      className="hover:bg-surface-800/30 transition-colors group"
                    >
                      <td className="p-4">
                        <span className="font-mono text-primary-light text-sm cursor-pointer hover:underline">{ticket.id}</span>
                      </td>
                      <td className="p-4 text-surface-50 font-medium">{ticket.title}</td>
                      <td className="p-4">
                        <div className="flex items-center gap-1.5">
                          {ticket.status === 'Open' && <AlertCircle size={14} className="text-primary" />}
                          {ticket.status === 'In Progress' && <Clock size={14} className="text-warning" />}
                          {ticket.status === 'Pending Approval' && <Clock size={14} className="text-surface-400" />}
                          {ticket.status === 'Closed' && <CheckCircle2 size={14} className="text-success" />}
                          <span className="text-sm text-surface-300">{ticket.status}</span>
                        </div>
                      </td>
                      <td className="p-4">
                        <span className={`inline-flex px-2 py-1 rounded text-xs font-bold ${
                          ticket.priority === 'Critical' ? 'bg-danger/10 text-danger border border-danger/20' : 
                          ticket.priority === 'High' ? 'bg-warning/10 text-warning border border-warning/20' : 
                          'bg-surface-800 text-surface-300 border border-surface-700'
                        }`}>
                          {ticket.priority}
                        </span>
                      </td>
                      <td className="p-4 text-sm text-surface-400">{ticket.type}</td>
                      <td className="p-4 text-sm text-surface-400">{ticket.created}</td>
                      <td className="p-4">
                        <div className="flex items-center gap-2">
                          <div className="w-6 h-6 rounded-full bg-surface-700 flex items-center justify-center text-[10px] font-bold text-surface-200">
                            {ticket.assignee.substring(0,2).toUpperCase()}
                          </div>
                          <span className="text-sm text-surface-300">{ticket.assignee}</span>
                        </div>
                      </td>
                    </motion.tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

        </div>
      </main>
    </div>
  );
}
